### ISSUE TITLE
can make no contribution, but still go through the contribot flow

### ISSUE THREAD

**Issue by nquinlan** [elbuo8/contribot#5]
from the contribot you have deployed right now, it seems I can go through the contribot flow by simply changing my username in a contribot URL. (e.g. `http://sg-contribot.herokuapp.com/auth/nquinlan`)

Contibot should probably check to make sure an accepted PR has been made, before directing someone to Github. (Either that or give each PR a unique hash, that only is redeemable by a certain user)

**Comment by elbuo8** [comment]
That has been implemented...The version running I have no clue when was the last time I updated it.  Was still debugging back then. I'll make sure to verify it in the last release. I need to move stuff away from ENV vars.

**Comment by elbuo8** [comment]
See if you can reproduce this yo.

**Comment by nquinlan** [comment]
I think it's now been dealt with.
