### ISSUE TITLE
should not reward repo contibutors

### ISSUE THREAD

**Issue by nquinlan** [elbuo8/contribot#8]
Contribot should check to ensure that the person we're rewarding is not already a contributor to the repo.

**Comment by elbuo8** [comment]
As in someone already added?

On Wednesday, May 14, 2014, Nick Quinlan notifications@github.com wrote:

> Contribot should check to ensure that the person we're rewarding is not
> already a contributor to the repo.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/elbuo8/contribot/issues/8
> .

## 

Yamil Asusta
@elbuo8 https://twitter.com/elbuo8

**Comment by nquinlan** [comment]
Yeah, exactly, sorry for the confusion. @brandonmwest and I were talking about that, for example, Gridders who have commit access shouldn't be rewarded.

**Comment by brandonmwest** [comment]
yeah there should be a way to blacklist orgs -- if user is part of sendgrid org, don't post

**Comment by elbuo8** [comment]
I had completely forgotten about that. Awesomeness. I will make a separate branch.

**Comment by elbuo8** [comment]
Fixed :)

https://github.com/elbuo8/contribot/commit/ef5fddb49e55ecbe53b47a628c2631c96463e2d1

Hooray!
